export const DUMMY_DATA = {
  totalRecords: 25,
  data: [
    {
      loadId: 3041984,
      orderId: 1924594,
      customerName: 'UNIVERSITY FURNISHINGS',
      customerId: 360114,
      referenceNumber: null,
      carrierName: 'Roadrunner Transportation Services',
      status: 'Dispatched',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'James Loyd',
      ownerId: 782174,
      assignedTo: 'James Loyd',
      accountManager: 'Demo Account',
      salesManager: 'Wilson Rodriguez',
      coveredBy: 'James Loyd',
      coveredById: 782174,
      origin: 'DENVER, NC',
      mode: 'TL',
      destination: 'MONROE, NC',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2023-02-18T12:00:00',
      pickUpTime: null,
      dropDate: '2023-02-21T12:00:00',
      dropOffTime: null,
      equipment: '',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: 65,
      assignedToId: 782174,
      loadNumber: '1924594-1',
    },
    {
      loadId: 3068705,
      orderId: 1948898,
      customerName: 'zAlbertsons AZ',
      customerId: 646418,
      referenceNumber: 'EDI_TEST_914109738',
      carrierName: null,
      status: 'Unassigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'System Notification',
      ownerId: 1,
      assignedTo: 'System Notification',
      accountManager: 'Marc Bodley',
      salesManager: 'Marc Bodley',
      coveredBy: ' ',
      coveredById: null,
      origin: 'GONZALES, CA',
      mode: 'TL',
      destination: 'SPOKANE, WA',
      pickUps: 4,
      dropOffs: 1,
      pickDate: '2024-10-06T12:00:00',
      pickUpTime: null,
      dropDate: '2024-10-11T12:00:00',
      dropOffTime: null,
      equipment: 'R',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: null,
      assignedToId: 1,
      loadNumber: '1948898-1',
    },
    {
      loadId: 3070162,
      orderId: 1950205,
      customerName: 'zAlbertsons AZ',
      customerId: 646418,
      referenceNumber: 'EDI_TEST_584827750',
      carrierName: null,
      status: 'Unassigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'System Notification',
      ownerId: 1,
      assignedTo: 'System Notification',
      accountManager: 'Marc Bodley',
      salesManager: 'Marc Bodley',
      coveredBy: ' ',
      coveredById: null,
      origin: 'SALINAS, CA',
      mode: 'TL',
      destination: 'SPOKANE, WA',
      pickUps: 3,
      dropOffs: 1,
      pickDate: '2024-10-13T12:00:00',
      pickUpTime: null,
      dropDate: '2024-10-18T12:00:00',
      dropOffTime: null,
      equipment: 'R',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: null,
      assignedToId: 1,
      loadNumber: '1950205-1',
    },
    {
      loadId: 1776511,
      orderId: 435643,
      customerName: 'ARMSTRONG TRANSPORT GROUP',
      customerId: 358231,
      referenceNumber: null,
      carrierName: 'Global Tranz Enterprises**Broker Only',
      status: 'Unassigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Aaron Thrift',
      ownerId: 763890,
      assignedTo: 'Aaron Thrift',
      accountManager: 'Aaron Thrift',
      salesManager: 'Aaron Thrift',
      coveredBy: 'Aaron Thrift',
      coveredById: 763890,
      origin: 'Charlotte, NC',
      mode: 'LTL',
      destination: 'Charlotte, NC',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2017-01-17T12:00:00',
      pickUpTime: null,
      dropDate: '2017-01-17T12:00:00',
      dropOffTime: null,
      equipment: 'V',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: 'plastic',
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: 0,
      assignedToId: 763890,
      loadNumber: '435643-1',
    },
    {
      loadId: 2958054,
      orderId: 1601293,
      customerName: 'Demo EDI Customer',
      customerId: 619930,
      referenceNumber: 'EdiUnitTestShipmentId_743650000',
      carrierName: null,
      status: 'Unassigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'System Notification',
      ownerId: 1,
      assignedTo: 'System Notification',
      accountManager: 'Rob Liss',
      salesManager: 'Mark Arce',
      coveredBy: ' ',
      coveredById: null,
      origin: 'ELK GROVE VILLAGE, IL',
      mode: 'TL',
      destination: 'BLOOMFIELD, MO',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2022-03-07T12:00:00',
      pickUpTime: null,
      dropDate: '2022-03-12T12:00:00',
      dropOffTime: null,
      equipment: 'F',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: null,
      assignedToId: 1,
      loadNumber: '1601293-1',
    },
    {
      loadId: 2962279,
      orderId: 1605200,
      customerName: 'Test 50',
      customerId: 524230,
      referenceNumber: null,
      carrierName: 'Old Dominion Freight Line, Inc',
      status: 'Assigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Joe Crachiolo',
      ownerId: 783959,
      assignedTo: 'Joe Crachiolo',
      accountManager: 'Demo Account',
      salesManager: 'Demo Account',
      coveredBy: 'Joe Crachiolo',
      coveredById: 783959,
      origin: 'Portland, OR',
      mode: 'LTL',
      destination: 'Douglas, GA',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2021-06-04T12:00:00',
      pickUpTime: '',
      dropDate: '2021-06-07T12:00:00',
      dropOffTime: null,
      equipment: 'F',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: 'stuff',
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: null,
      assignedToId: 783959,
      loadNumber: '1605200-1',
    },
    {
      loadId: 2963049,
      orderId: 1605899,
      customerName: 'Sysco Corp',
      customerId: 783452,
      referenceNumber: 'EdiUnitTestShipmentId_48250150',
      carrierName: null,
      status: 'Unassigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Shawn Saras',
      ownerId: 783420,
      assignedTo: 'Shawn Saras',
      accountManager: 'Parvesh Kumar',
      salesManager: 'Marc Bodley',
      coveredBy: ' ',
      coveredById: null,
      origin: 'PLYMOUTH, WI',
      mode: 'TL',
      destination: 'LINCOLN, NE',
      pickUps: 3,
      dropOffs: 1,
      pickDate: '2022-04-15T12:00:00',
      pickUpTime: null,
      dropDate: '2022-04-20T12:00:00',
      dropOffTime: null,
      equipment: 'V',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: null,
      assignedToId: 783420,
      loadNumber: '1605899-1',
    },
    {
      loadId: 2964131,
      orderId: 1606891,
      customerName: 'Leprino Foods',
      customerId: 624749,
      referenceNumber: '125209417_QA_TC',
      carrierName: null,
      status: 'Unassigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Shawn Saras',
      ownerId: 783420,
      assignedTo: 'Shawn Saras',
      accountManager: 'Travis Brewer',
      salesManager: 'Travis Brewer',
      coveredBy: ' ',
      coveredById: null,
      origin: 'FOWLER, CA',
      mode: 'TL',
      destination: 'TRACY, CA',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2021-05-10T12:00:00',
      pickUpTime: null,
      dropDate: '2021-05-11T12:00:00',
      dropOffTime: null,
      equipment: '',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: null,
      assignedToId: 783420,
      loadNumber: '1606891-1',
    },
    {
      loadId: 3039548,
      orderId: 1922395,
      customerName: 'Laurens Video Game Store',
      customerId: 781617,
      referenceNumber: '',
      carrierName: null,
      status: 'Unassigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Thy Duong',
      ownerId: 783973,
      assignedTo: 'Thy Duong',
      accountManager: 'Parvesh Kumar Org',
      salesManager: 'Parvesh Kumar Org',
      coveredBy: 'Thy Duong',
      coveredById: 783973,
      origin: 'Charlotte, NC',
      mode: 'TL',
      destination: 'Silver Spring, MD',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2023-09-10T12:00:00',
      pickUpTime: '',
      dropDate: '2023-09-11T12:00:00',
      dropOffTime: '',
      equipment: 'F',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: 405,
      assignedToId: 783973,
      loadNumber: '1922395-1',
    },
    {
      loadId: 3039611,
      orderId: 1922458,
      customerName: 'Laurens Video Game Store',
      customerId: 781617,
      referenceNumber: '',
      carrierName: null,
      status: 'Unassigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Thy Duong',
      ownerId: 783973,
      assignedTo: 'Thy Duong',
      accountManager: 'Parvesh Kumar Org',
      salesManager: 'Parvesh Kumar Org',
      coveredBy: 'Thy Duong',
      coveredById: 783973,
      origin: 'Charlotte, NC',
      mode: 'TL',
      destination: 'Silver Spring, MD',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2023-09-01T12:00:00',
      pickUpTime: '',
      dropDate: '2023-09-20T12:00:00',
      dropOffTime: null,
      equipment: 'F',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: 405,
      assignedToId: 783973,
      loadNumber: '1922458-1',
    },
    {
      loadId: 3049558,
      orderId: 1931290,
      customerName: 'HelloFresh',
      customerId: 795383,
      referenceNumber: null,
      carrierName: null,
      status: 'Unassigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Parvesh Kumar',
      ownerId: 783971,
      assignedTo: 'Parvesh Kumar',
      accountManager: 'Scot Thompson',
      salesManager: 'Scot Thompson',
      coveredBy: 'Parvesh Kumar',
      coveredById: 783971,
      origin: 'Charlotte, NC',
      mode: 'TL',
      destination: 'Charlotte, NC',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2023-04-14T12:00:00',
      pickUpTime: null,
      dropDate: '2023-04-21T12:00:00',
      dropOffTime: null,
      equipment: 'F/SD',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: 0,
      assignedToId: 783971,
      loadNumber: '1931290-1',
    },
    {
      loadId: 3058257,
      orderId: 1939114,
      customerName: 'Laurens Video Game Store',
      customerId: 781617,
      referenceNumber: null,
      carrierName: 'Blue Ice Transport Inc',
      status: 'Assigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Katie ElHamahmy',
      ownerId: 783969,
      assignedTo: 'Katie ElHamahmy',
      accountManager: 'Parvesh Kumar Org',
      salesManager: 'Parvesh Kumar Org',
      coveredBy: 'Katie ElHamahmy',
      coveredById: 783969,
      origin: 'Charlotte, NC',
      mode: 'TL',
      destination: 'Charlotte, NC',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2023-06-23T12:00:00',
      pickUpTime: null,
      dropDate: '2023-06-26T12:00:00',
      dropOffTime: null,
      equipment: '',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: 0,
      assignedToId: 783969,
      loadNumber: '1939114-1',
    },
    {
      loadId: 3065874,
      orderId: 1946361,
      customerName: 'Lulu the Customer',
      customerId: 804646,
      referenceNumber: null,
      carrierName: null,
      status: 'Unassigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'John Economou',
      ownerId: 784116,
      assignedTo: 'John Economou',
      accountManager: 'James David',
      salesManager: 'Mike Edmondson',
      coveredBy: 'John Economou',
      coveredById: 784116,
      origin: 'Northbrook, IL',
      mode: 'TL',
      destination: 'Milwaukee, WI',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2023-08-17T12:00:00',
      pickUpTime: null,
      dropDate: '2023-08-17T12:00:00',
      dropOffTime: null,
      equipment: 'DD',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: 69,
      assignedToId: 784116,
      loadNumber: '1946361-1',
    },
    {
      loadId: 3046999,
      orderId: 1925830,
      customerName: 'James Thomas Loyd',
      customerId: 800137,
      referenceNumber: '123456',
      carrierName: 'Blue Ice Transport Inc',
      status: 'Assigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Albert Huynh',
      ownerId: 784248,
      assignedTo: 'Albert Huynh',
      accountManager: 'James Loyd',
      salesManager: 'James Loyd',
      coveredBy: 'Albert Huynh',
      coveredById: 784248,
      origin: null,
      mode: 'TL',
      destination: null,
      pickUps: 1,
      dropOffs: 2,
      pickDate: null,
      pickUpTime: null,
      dropDate: null,
      dropOffTime: null,
      equipment: 'V53',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: 'Chips And Dip',
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: 2349,
      assignedToId: 784248,
      loadNumber: '1925830-2',
    },
    {
      loadId: 2993039,
      orderId: 1632432,
      customerName: 'Test Customer 88938',
      customerId: 362140,
      referenceNumber: null,
      carrierName: 'Forward Air',
      status: 'Assigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Jen White',
      ownerId: 783921,
      assignedTo: 'Jen White',
      accountManager: 'System Notification',
      salesManager: 'System Notification',
      coveredBy: 'Jen White',
      coveredById: 783921,
      origin: 'Huntersville, NC',
      mode: 'LTL',
      destination: 'Harrisburg, NC',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2022-02-25T05:00:00',
      pickUpTime: null,
      dropDate: '2022-02-25T05:00:00',
      dropOffTime: null,
      equipment: '',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: null,
      assignedToId: 783921,
      loadNumber: '1632432-1',
    },
    {
      loadId: 2995120,
      orderId: 1634325,
      customerName: 'Tillamook County Creamery Association',
      customerId: 561414,
      referenceNumber: 'BlueJayProviderTEST',
      carrierName: null,
      status: 'Unassigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Mark Taylor',
      ownerId: 783697,
      assignedTo: 'Mark Taylor',
      accountManager: 'James Dolan',
      salesManager: 'James Dolan',
      coveredBy: ' ',
      coveredById: null,
      origin: 'MOUNTAIN HOME, ID',
      mode: 'TL',
      destination: 'MIRA LOMA, CA',
      pickUps: 1,
      dropOffs: 3,
      pickDate: '2022-03-01T12:00:00',
      pickUpTime: null,
      dropDate: '2022-03-03T12:00:00',
      dropOffTime: null,
      equipment: 'R53',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: null,
      assignedToId: 783697,
      loadNumber: '1634325-1',
    },
    {
      loadId: 2984466,
      orderId: 1624747,
      customerName: 'Laurens Video Game Store',
      customerId: 781617,
      referenceNumber: null,
      carrierName: 'Customized Logistics Group DBA Logistics Titans',
      status: 'Dispatched',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Leigh Taylor',
      ownerId: 570191,
      assignedTo: 'Leigh Taylor',
      accountManager: 'Parvesh Kumar Org',
      salesManager: 'Parvesh Kumar Org',
      coveredBy: 'Leigh Taylor',
      coveredById: 570191,
      origin: 'Johnson City, TN',
      mode: 'LTL',
      destination: 'Charlotte, NC',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2022-01-19T12:00:00',
      pickUpTime: null,
      dropDate: '2022-01-19T12:00:00',
      dropOffTime: null,
      equipment: '',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: 161,
      assignedToId: 570191,
      loadNumber: '1624747-1',
    },
    {
      loadId: 3005027,
      orderId: 1643215,
      customerName: 'A & K Railroad Materials',
      customerId: 783994,
      referenceNumber: null,
      carrierName: 'XPO Logistics',
      status: 'Assigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Parvesh Kumar',
      ownerId: 783971,
      assignedTo: 'Parvesh Kumar',
      accountManager: 'Eric Covington',
      salesManager: 'Eric Covington',
      coveredBy: 'Parvesh Kumar',
      coveredById: 783971,
      origin: 'SILVER SPRING, MD',
      mode: 'LTL',
      destination: 'Jacksonville, FL',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2022-05-14T12:00:00',
      pickUpTime: null,
      dropDate: '2022-05-28T12:00:00',
      dropOffTime: null,
      equipment: '',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: null,
      assignedToId: 783971,
      loadNumber: '1643215-1',
    },
    {
      loadId: 3005525,
      orderId: 1643664,
      customerName: 'Tillamook County Creamery Association',
      customerId: 561414,
      referenceNumber: '123609',
      carrierName: null,
      status: 'Unassigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Parvesh Kumar',
      ownerId: 783971,
      assignedTo: 'Parvesh Kumar',
      accountManager: 'James Dolan',
      salesManager: 'James Dolan',
      coveredBy: ' ',
      coveredById: null,
      origin: 'MOUNTAIN HOME, ID',
      mode: 'TL',
      destination: 'TERRELL, TX',
      pickUps: 1,
      dropOffs: 2,
      pickDate: '2022-05-19T12:00:00',
      pickUpTime: null,
      dropDate: '2022-05-23T12:00:00',
      dropOffTime: null,
      equipment: 'R53',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: null,
      assignedToId: 783971,
      loadNumber: '1643664-1',
    },
    {
      loadId: 3007377,
      orderId: 1645315,
      customerName: 'Oatly Salt Lake Division',
      customerId: 799398,
      referenceNumber: '144016931_SHAWN_00',
      carrierName: null,
      status: 'Unassigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Shawn Saras',
      ownerId: 783420,
      assignedTo: 'Shawn Saras',
      accountManager: 'Tiffany Ladish',
      salesManager: 'Tiffany Ladish',
      coveredBy: ' ',
      coveredById: null,
      origin: 'OGDEN, UT',
      mode: 'TL',
      destination: 'TEMPLE, TX',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2022-05-24T12:00:00',
      pickUpTime: null,
      dropDate: '2022-05-26T12:00:00',
      dropOffTime: null,
      equipment: 'R53',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: null,
      assignedToId: 783420,
      loadNumber: '1645315-1',
    },
    {
      loadId: 3008731,
      orderId: 1646534,
      customerName: 'Danone NA',
      customerId: 790197,
      referenceNumber: '144311785_20220608_00',
      carrierName: null,
      status: 'Unassigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Shawn Saras',
      ownerId: 783420,
      assignedTo: 'Shawn Saras',
      accountManager: 'Jesse Longoria',
      salesManager: 'Jesse Longoria',
      coveredBy: ' ',
      coveredById: null,
      origin: 'SPEARFISH, SD',
      mode: 'TL',
      destination: 'MOUNT CRAWFORD, VA',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2022-06-02T12:00:00',
      pickUpTime: null,
      dropDate: '2022-06-06T12:00:00',
      dropOffTime: null,
      equipment: 'V',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: null,
      assignedToId: 783420,
      loadNumber: '1646534-1',
    },
    {
      loadId: 3015701,
      orderId: 1652797,
      customerName: 'Lauren s Video Game Store',
      customerId: 781617,
      referenceNumber: null,
      carrierName: 'Roadrunner Transportation Services',
      status: 'Dispatched',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Katie ElHamahmy',
      ownerId: 783969,
      assignedTo: 'Katie ElHamahmy',
      accountManager: 'Parvesh Kumar Org',
      salesManager: 'Parvesh Kumar Org',
      coveredBy: 'Katie ElHamahmy',
      coveredById: 783969,
      origin: 'Atlanta, GA',
      mode: 'LTL',
      destination: 'Fort Mill, SC',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2022-07-28T12:00:00',
      pickUpTime: null,
      dropDate: '2022-07-29T12:00:00',
      dropOffTime: null,
      equipment: '',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: null,
      assignedToId: 783969,
      loadNumber: '1652797-1',
    },
    {
      loadId: 3021695,
      orderId: 1658177,
      customerName: 'Pixelle Specialty Solutions',
      customerId: 795206,
      referenceNumber: '842536793_00_01',
      carrierName: null,
      status: 'Unassigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Srini R',
      ownerId: 783972,
      assignedTo: 'Srini R',
      accountManager: 'Warm Lead',
      salesManager: 'Warm Lead',
      coveredBy: ' ',
      coveredById: null,
      origin: 'SPRING GROVE, PA',
      mode: 'TL',
      destination: 'MONROE, WI',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2022-08-23T12:00:00',
      pickUpTime: null,
      dropDate: '2022-08-24T12:00:00',
      dropOffTime: null,
      equipment: 'F',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: null,
      assignedToId: 783972,
      loadNumber: '1658177-1',
    },
    {
      loadId: 3032641,
      orderId: 1916211,
      customerName: 'Hormel Foods',
      customerId: 802491,
      referenceNumber: 'testJ10',
      carrierName: null,
      status: 'Unassigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'John Economou',
      ownerId: 784116,
      assignedTo: 'John Economou',
      accountManager: 'William Webb',
      salesManager: 'William Webb',
      coveredBy: ' ',
      coveredById: null,
      origin: 'WOODVILLE, WI',
      mode: 'TL',
      destination: 'CHEYENNE, WY',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2023-11-09T12:00:00',
      pickUpTime: null,
      dropDate: '2023-11-11T12:00:00',
      dropOffTime: null,
      equipment: 'F',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: 514447,
      miles: null,
      assignedToId: 784116,
      loadNumber: '1916211-1',
    },
    {
      loadId: 3034619,
      orderId: 1917976,
      customerName: 'A & K Railroad Materials',
      customerId: 783994,
      referenceNumber: null,
      carrierName: 'TForce Freight',
      status: 'Assigned',
      office: 'ATG Corp',
      officeId: 63,
      owner: 'Parvesh Kumar',
      ownerId: 783971,
      assignedTo: 'Parvesh Kumar',
      accountManager: 'Eric Covington',
      salesManager: 'Eric Covington',
      coveredBy: 'Parvesh Kumar',
      coveredById: 783971,
      origin: 'Toledo, OH',
      mode: 'LTL',
      destination: 'SILVER SPRING, MD',
      pickUps: 1,
      dropOffs: 1,
      pickDate: '2022-12-22T12:00:00',
      pickUpTime: null,
      dropDate: '2022-12-22T12:00:00',
      dropOffTime: null,
      equipment: '',
      flagId: null,
      flagText: null,
      flagType: null,
      claim: false,
      assignedToGroupId: null,
      product: null,
      lastCheckCallDate: null,
      lastCheckCallComment: null,
      sharedWithOfficeId: null,
      confirmationSigned: false,
      postingId: null,
      miles: 467,
      assignedToId: 783971,
      loadNumber: '1917976-1',
    },
  ],
  permissionGranted: true,
};
