name: Build on Pull Request

# This workflow is triggered on pull requests to the repository
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist